/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TelaRelatorio.java
 *
 * Created on Feb 17, 2019, 9:15:31 AM
 */

package telas;

import bd.ClienteBD;
import bd.QuimicaBD;
import bd.RelatorioBD;
import bd.ServicoBD;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import modelo.Cliente;
import modelo.Quimica;
import modelo.Relatorio;
import modelo.Servico;

/**
 *
 * @author Skynet
 */
public class TelaRelatorio extends javax.swing.JFrame {
    private DefaultTableModel dtm;
    private RelatorioBD relatorioBD = new RelatorioBD();
    private ServicoBD servicoBD = new ServicoBD();
    private ClienteBD clienteBD = new ClienteBD();

    private List<Relatorio> listaRelatorio = new ArrayList<Relatorio>();
    private List<Servico> listaServico = new ArrayList<Servico>();
    private List<Cliente> listaCliente = new ArrayList<Cliente>();

    /** Creates new form TelaRelatorio */
    public TelaRelatorio() {
        initComponents();

        listaRelatorio = relatorioBD.getDatas(null,1);
        dtm = (DefaultTableModel) tabela.getModel();
        for (Relatorio relatorio:listaRelatorio){
            dtm.insertRow(dtm.getRowCount(),new Object[]{relatorio.getData(),relatorio.getNmeCliente(),relatorio.getCorte(),relatorio.getBarba(),relatorio.getSobran(),relatorio.getQuimica()});
        }

        listaCliente = clienteBD.getClientes();
        for (Cliente  cliente : listaCliente){
            comboCliente.addItem(cliente.getNome());
        }

        listaServico = servicoBD.getServicos();
        for (Servico servico : listaServico){
            if(!servico.getDescricao().equals("Cortesia") && !servico.getDescricao().equals("Barba fixo"))
            comboServico.addItem(servico.getDescricao());
        }

      
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        comboCliente = new componentes.UJComboBox();
        btnConfirma = new javax.swing.JButton();
        comboServico = new componentes.UJComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        btnFechar = new javax.swing.JButton();

        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(-12566464,true));
        jPanel1.setAutoscrolls(true);

        comboCliente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cliente" }));
        comboCliente.setAutocompletar(true);

        btnConfirma.setText("Confirmar");
        btnConfirma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmaActionPerformed(evt);
            }
        });

        comboServico.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Servico" }));
        comboServico.setAutocompletar(true);

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data", "Nome", "Corte", "Barba", "Sobrancelhas", "Quimica"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela.setColumnSelectionAllowed(true);
        tabela.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabela);
        tabela.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabela.getColumnModel().getColumn(0).setResizable(false);
        tabela.getColumnModel().getColumn(1).setResizable(false);
        tabela.getColumnModel().getColumn(2).setResizable(false);
        tabela.getColumnModel().getColumn(3).setResizable(false);
        tabela.getColumnModel().getColumn(4).setResizable(false);
        tabela.getColumnModel().getColumn(5).setResizable(false);

        btnFechar.setFont(new java.awt.Font("Dialog", 0, 14));
        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 633, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(comboCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboServico, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 274, Short.MAX_VALUE)
                        .addComponent(btnConfirma, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(542, Short.MAX_VALUE)
                .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(comboCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnConfirma, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(comboServico, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnFechar, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnConfirmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmaActionPerformed
        int filtro = 5;
        dtm.setRowCount(0);
        if(comboServico.getSelectedItem().toString().equals("corte")){
            filtro = 2;
            dtm.setRowCount(0);
            listaRelatorio = relatorioBD.getDatas(null, filtro);
        }

         if(comboServico.getSelectedItem().toString().equals("barba")){
            filtro = 3;
            dtm.setRowCount(0);
            listaRelatorio = relatorioBD.getDatas(null, filtro);
        }


         if(comboServico.getSelectedItem().toString().equals("Sobrancelhas")){
            filtro = 4;
            dtm.setRowCount(0);
            listaRelatorio = relatorioBD.getDatas(null, filtro);
        }
        if(!comboCliente.getSelectedItem().equals("Cliente")){
            filtro +=4;
            Cliente c = clienteBD.getClienteNome(comboCliente.getSelectedItem().toString());
            listaRelatorio = relatorioBD.getDatasEspc(null, filtro, c);
        }
        if(comboCliente.getSelectedItem().equals("Cliente") && comboServico.getSelectedItem().equals("Nada")){
            filtro = 10;
            listaRelatorio = relatorioBD.getDatas(null, filtro);
        }

         for (Relatorio relatorio:listaRelatorio){
            dtm.insertRow(dtm.getRowCount(),new Object[]{relatorio.getData(),relatorio.getNmeCliente(),relatorio.getCorte(),relatorio.getBarba(),relatorio.getSobran(),relatorio.getQuimica()});
        }
    }//GEN-LAST:event_btnConfirmaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirma;
    private javax.swing.JButton btnFechar;
    private componentes.UJComboBox comboCliente;
    private componentes.UJComboBox comboServico;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables

}
